version: '3'

services:
  cs:
    container_name: cs
    build: .
    env_file: .env
    volumes:
      - ./podbot/podbot.cfg:/opt/hlds/cstrike/addons/podbot/podbot.cfg
    ports:
      - '27015:27015/udp'
